#pragma config(Motor,  port2,           right_drive_motor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           arm_motor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           claw_motor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          left_drive_motor, tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Drive.h"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}


task autonomous()
{

	AutonomousCodePlaceholderForTesting();
}


task usercontrol()
{

	while (true)
	{
		updateDrive();
		updateOI();
	}
}
